### ISSUE TITLE
Error 401 Unauthorized

### ISSUE THREAD

**Issue by sergiooncode** [IHTSDO/authoring-services#16]
Hello,
First of all, thanks for sharing the SNOMED tooling as open source. I work for a company called <a href="https://www.savanamed.com/" target="_blank">Savana Medica</a> that does NLP on Electronic Medical Records to extract medical meaning. We partner up with hospitals so they can do clinical research based on "clinical databases" we extract for them out of their EMR docs and later publish research studies. It's a fascinating project. We use SNOMED terminology in the process and we've been doing it for a few years already. We have doctors on staff who have expertise on specific medical areas who help us improve the terminology so we "read" better and extract meaning more specific and accurate. These terminology improvements happen for each of the mentioned studies and eventually after some curation by our doctors they get merged in the terminology "master branch". To be honest SNOMED is quite up-to-date on each release so in between releases we just update a few concepts here and there or maybe add a couple of specific concepts. Our plan is not strictly to publish SNOMED extensions but it'd be useful be able to work the way SNOMED works for our use-case, that is using branches for the different studies, opening "Pull-Requests" for concepts that our doctors will review, etc so we considered trying to use the open-source tooling code in your repos since SNOMED tools follow best terminology practices and doing that'd save us quite a bit of dev effort.

Our plan is to use these three blocks:
<img width="395" alt="Screenshot 2021-02-10 at 19 39 26" src="https://user-images.githubusercontent.com/513989/107555809-e8095b00-6bd7-11eb-91c9-0614fe31af45.png">

The issue I'm currently facing happens when trying to run the authoring-services backend, I see the errors below which show in different forms based on the values set for Jira in the application.properties:
```Java
2021-02-10 17:38:06.936  INFO 1 --- [           main] o.i.s.a.single.api.service.TaskService   : Fetching Jira custom field names.
2021-02-10 17:38:07.884 ERROR 1 --- [           main] o.i.s.a.single.api.service.TaskService   : net.rcarz.jiraclient.RestException: 401 Unauthorized:
```
```Java
2021-02-10 16:53:07.297  INFO 1 --- [           main] o.i.s.a.single.api.service.TaskService   : Fetching Jira custom field names.
2021-02-10 16:53:08.196 ERROR 1 --- [           main] o.i.s.a.single.api.service.TaskService   : net.rcarz.jiraclient.RestException: 401 Unauthorized: oauth_problem=signature_invalid&oauth_signature=MgFgfI3q1bpsyRnawOWUnxaJ5gqis3iRaUpzOFyMHQFYgVLAoO8CjdM%2BlePv9oehJb8Gg5RhuD9P6ELUbyHfBi8w7T8lLo57YDnwk4qCY%2BuPA2QIe7IlC25QJRds1qPIuOrJMYjDaEFEnkAY3%2BiFsuDnSOYAstrVC1p5wGScjKE%3D&oauth_signature_base_string=GET%26https%253A%252F%252Fserpeartestdev.atlassian.net%252Frest%252Fapi%252Flatest%252Ffield%26oauth_consumer_key%253DOauthKey%2526oauth_nonce%253D21435065434080.059592019771540494%2526oauth_signature_method%253DRSA-SHA1%2526oauth_timestamp%253D1612975987%2526oauth_token%253D%2526user_id%253D&oauth_signature_method=RSA-SHA1
```
(the second log lines I added doing `logger.error(String.valueOf(e));` on the exc handler)

I generated the private-public key pair following this [tutorial](https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-oauth-authentication/). Most probably I'm not setting the values correctly in the configuration.

Any help you can provide will be much appreciated.

**Comment by kaicode** [comment]
Hi @sperez4mba, 
Thank you for getting in touch about your issue and also it's really nice to hear about your project it sounds like very valuable work!

We have a little extra documentation in this area which I have just noticed it not linked from the docs on this repo:
[Authoring Platform JIRA Setup](https://confluence.ihtsdotools.org/display/TOOLS/Authoring+Platform+JIRA+Setup).
Please follow the steps outlined there to see if that helps. If you are still stuck do get back in touch, I can provide screenshots of our current jira configuration if needed. We are using Jira 8 hosted on a server (not cloud), but I believe the setup for Jira 7 which is in the linked documentation is the same.

I hope that helps, let us know either way 👍 

Kai Kewley

**Comment by sergiooncode** [comment]
Hi @kaicode,
Thanks for the shared details, it was really helpful. Actually at first I was trying to make it work on Jira Cloud but I couldn't so after your comment I decided to deploy Jira 8 on a server using a docker image and it worked like a charm. A big difference I see between Jira Cloud (not sure what version that is since they don't seem to show it in the footer anymore) and Jira 8 is that on Jira Cloud in the Application link - Incoming Authentication configuration the following arguments are simply not there: Allow 2-Legged OAuth, Execute as and Allow user impersonation through 2-Legged OAuth.

Currently I'm trying to deploy the authoring-ui application, I may have some questions so I'll ask in the corresponding repo.

Thanks again,
Sergio

**Comment by kaicode** [comment]
Hey @sperez4mba,
Glad you got Authoring Services authenticated with Jira using a standalone deployment.
Thank you for sharing these details with the community, no doubt this will be helpful for someone 👍 

FYI - The reason we need this low level authentication is to allow Authoring Services to view projects and make changes in Jira as the authoring platform user using just their username.

Cheers
Kai

**Comment by tandara0** [comment]
> Hi @kaicode, Thanks for the shared details, it was really helpful. Actually at first I was trying to make it work on Jira Cloud but I couldn't so after your comment I decided to deploy Jira 8 on a server using a docker image and it worked like a charm. A big difference I see between Jira Cloud (not sure what version that is since they don't seem to show it in the footer anymore) and Jira 8 is that on Jira Cloud in the Application link - Incoming Authentication configuration the following arguments are simply not there: Allow 2-Legged OAuth, Execute as and Allow user impersonation through 2-Legged OAuth.
> 
> Currently I'm trying to deploy the authoring-ui application, I may have some questions so I'll ask in the corresponding repo.
> 
> Thanks again, Sergio

Dear @sergiooncode 

Our company has a similar issue. 
Your question has been of great help to us. 
We are very grateful to you.

However, I have a question about one of your posts.
 As a result, was the connection using 2-Legged OAuth successful in Jira Cloud? 
If so, can you tell me specifically how you did it?
