### ISSUE TITLE
Maven deps not solved ? otf-common:jar:4.1.1

### ISSUE THREAD

**Issue by Myu-Unix** [IHTSDO/authoring-services#6]
Hello, I am trying to deply the authoring-services (tried both master and develop) but these deps are not solved by mvn.

Do you know any way around that or is the file not on ihtsdotools.org servers anymore ?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.068 s
[INFO] Finished at: 2020-08-31T13:48:19Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project authoring-services: Could not resolve dependencies for project org.snomed.authoring:authoring-services:jar:5.22.2-SNAPSHOT: Failure to find org.ihtsdo.otf.common:otf-common:jar:4.1.1 in https://maven.ihtsdotools.org/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of ihtsdo-releases has elapsed or updates are forced -> [Help 1]
```

Cheers !

**Comment by kaicode** [comment]
Hi @Myu-Unix, sorry for this maven build problem.

We had not completed the migration to a new maven nexus server in all projects. This project is now using the new nexus3 maven server and the otf-common library that is needed is there.

Please pull master and try again.

Kind regards,
Kai

**Comment by Myu-Unix** [comment]
Thank you very much @kaicode ! I'll try this out :)
