### ISSUE TITLE
spellcheck jar and path-uri-rewrite-filter jar MIA 

### ISSUE THREAD

**Issue by rolance** [IHTSDO/authoring-services#9]
I can see that these artifacts have been downloaded to my .m2/repository (and re-downloaded when deleted) but am still getting the following when I run "mvn clean install" . 

`[ERROR] Failed to execute goal on project authoring-services: Could not resolve dependencies for project org.snomed.authoring:authoring-services:jar:5.22.1: The following artifacts could not be resolved: org.ihtsdo.otf:spellcheck-core:jar:1.1.1, org.snomed.otf:snomed-boot:jar:1.2.0, io.kaicode:branch-path-uri-rewrite-filter:jar:1.0.1: Failure to find org.ihtsdo.otf:spellcheck-core:jar:1.1.1 in https://nexus3.ihtsdotools.org/repository/maven-releases/ was cached in the local repository, resolution will not be reattempted until the update interval of ihtsdo-releases has elapsed or updates are forced`

**Comment by kaicode** [comment]
@rolance thank you for getting in touch and bringing this build issue to our attention.
The libraries have now been added to our nexus3 release repository.
Please run the build again including the -U parameter to force maven to pull dependency updates.
```
mvn clean install -U
```
Kind regards,
Kai Kewley
